services:
  stats-server:
    restart: on-failure:3
    build:
      context: ./ewm-stats-service/stats-server
      dockerfile: Dockerfile
    image: stats
    container_name: "ewm-stats-server"
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9090/actuator/health || exit 1" ]
      timeout: 10s
      interval: 30s
      retries: 3
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  stats-db:
    image: postgres:16.1
    container_name: postgres-ewm-stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-service:
    restart: on-failure:3
    build:
      context: ./ewm-main-service
      dockerfile: Dockerfile
    image: ewm-main-service
    container_name: "ewm-main-service"
    ports:
      - "8080:8080"
    depends_on:
      main-db:
        condition: service_healthy
      stats-server:
        condition: service_healthy
    environment:
      - STATS_SERVER_URL=http://ewm-stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/main_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  main-db:
    image: postgres:14-alpine
    container_name: "main-db"
    ports:
      - "6542:5432"
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
    environment:
      - POSTGRES_DB=main_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root