CREATE TABLE IF NOT EXISTS hits -- Создание таблицы statistics, если она не существует
(
    id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- Автоинкрементный первичный ключ
    app       VARCHAR(64) NOT NULL, -- Название сервиса/приложения (обязательное поле)
    uri       VARCHAR(64) NOT NULL, -- URI запроса (обязательное поле)
    ip        VARCHAR(64) NOT NULL, -- IP-адрес клиента (обязательное поле)
    created TIMESTAMP   NOT NULL -- Временная метка запроса (обязательное поле)
);