CREATE TABLE IF NOT EXISTS users -- Создание таблицы statistics, если она не существует
(
    id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(55) NOT NULL,
    email       VARCHAR(250) NOT NULL UNIQUE,

);