spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ewm_db
    username: postgres
    password: your_actual_password_here  # Replace with real password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect