statsserver:
      url: http://localhost:9090
server:
  port: 8080

spring:
  application:
    name: ewm-service
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: always

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6542/main_db
    username: root
    password: root

liquibase:
  enabled: true
  change-log: classpath:db/changelog/db.changelog-master.yaml